### ISSUE TITLE
HDF5 1.10 support

### ISSUE THREAD

**Issue by philippeVerney** [F2I-Consulting/etpServer-docker#1]
Hi Mathieu,

If possible, the built HDF5 library should be a 1.10.
The latest 1.10 would be my preference.

Thanks
Philippe

**Comment by philippeVerney** [comment]
It also looks that the HDF5 built produces much more than just the C library.
If possible, we should clean that in order not to produce the bin directory neither the hl library.

**Comment by mpoudret** [comment]
Hi Philippe,

The built HDF5 library is now latest 1.10 (1.10.5).

Regards,
Mathieu
