### ISSUE TITLE
NOCRYPT definition really useful?

### ISSUE THREAD

**Issue by philippeVerney** [F2I-Consulting/etpServer-docker#2]
Hi Mathieu,

I am wondering if the NOCRYPT definition in the beginning of the docker file is really useful.
I think it was here for minizip build. But we use minizip package now.
Can you try to remove it please?

Thanks

**Comment by philippeVerney** [comment]
I am a bit wondering the same about : pcre-devel and byacc packages.
Could you comment what there are for in the dockerfile please for maintenance reason. And if possible for other dependencies (for example wget which I know is useful for using a single docker RUN command)

**Comment by mpoudret** [comment]
Hi Philippe,

I successfully removed the NOCRYPT definition. I also cleaned the docker file by looking for unusefull packages. Purpose of remaning packages have been commented.

Regards,
Mathieu
